apiVersion: v1
kind: Service
metadata:
  name: {{ template "nats.fullname" . }}
  labels:
    app: {{ template "nats.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "nats.fullname" . }}-nats
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type "LoadBalancer" -}} {{ if .Values.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end -}}
  {{- end -}}
  selector:
    component: {{ template "nats.fullname" . }}-nats
{{ if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP | quote  }}
{{ end }}
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
