apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    redis-node: "true"
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas.slave }}
  template:
    metadata:
      labels:
        redis-node: "true"
        name: redis
        role: replica
{{ include "labels.standard" . | indent 8 }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis_image }}"
        resources:
{{ toYaml .Values.resources.slave | indent 10 }}

        readinessProbe:
          exec:
            command: 
            # - "true"
              - sh
              - -c
              # - "redis-cli info |grep -q 'role:master'"
              - "redis-cli info|grep -q $(redis-cli -h redis-sentinel -p 26379 --raw  sentinel master mymaster|grep runid -A1|tail -1)"

        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
      - name: data
      {{- if .Values.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistentVolume.existingClaim }}{{ .Values.persistentVolume.existingClaim }}{{- else }}{{ template "fullname" . }}{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
